# Generated by Django 5.0.1 on 2024-03-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauserinformations',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
