# Generated by Django 5.0.1 on 2024-03-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_company_app', '0004_alter_company_contact_person_phone'),
        ('users', '0008_extrauserinformations_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrauserinformations',
            name='favorite_company',
            field=models.ManyToManyField(blank=True, related_name='favorite_companies', to='user_company_app.company'),
        ),
    ]
