# Generated by Django 5.0.1 on 2024-03-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_extrauserinformations_favorite_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrauserinformations',
            name='user_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user_pics'),
        ),
    ]
