# Generated by Django 5.0.1 on 2024-03-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_extrauserinformations_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauserinformations',
            name='user_pic',
            field=models.ImageField(blank=True, default='images/defaultprofilepic.jpg', null=True, upload_to='user_pics'),
        ),
    ]
