# Generated by Django 5.0.1 on 2024-03-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_extrauserinformations_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauserinformations',
            name='user_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user_pics'),
        ),
    ]
