# Generated by Django 5.0.1 on 2024-03-12 17:03

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_extrauserinformations_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauserinformations',
            name='user_pic',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path),
        ),
    ]
