# Generated by Django 5.0.1 on 2024-04-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_extrauserinformations_user_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrauserinformations',
            name='date_of_birth',
        ),
    ]
