# Generated by Django 5.0.1 on 2024-03-15 17:53

import create_declaration.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_company_app', '0005_company_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_content', models.TextField()),
                ('company_stamp', models.ImageField(blank=True, null=True, upload_to=create_declaration.models.company_stamp_path)),
                ('extend_company_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_company_app.company')),
            ],
        ),
    ]
