# Generated by Django 5.0.1 on 2024-03-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_declaration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendcompanymodel',
            name='pdf_declaration',
            field=models.FileField(blank=True, null=True, upload_to='pdf_declarations'),
        ),
    ]
