# Generated by Django 5.0.1 on 2024-03-15 18:08

import create_declaration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_declaration', '0002_extendcompanymodel_pdf_declaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendcompanymodel',
            name='pdf_declaration',
            field=models.FileField(blank=True, null=True, upload_to=create_declaration.models.pdf_declaration_path),
        ),
    ]
