# Generated by Django 5.0.1 on 2024-03-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_declaration', '0004_extendcompanymodel_default_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendcompanymodel',
            name='default_content',
        ),
    ]
