# Generated by Django 5.0.1 on 2024-04-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_declaration', '0006_alter_extendcompanymodel_declaration_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendCompanyModel',
        ),
    ]
