# Generated by Django 5.0.1 on 2024-03-02 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_declaratie_app', '0004_alter_extrauserinfo_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauserinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extrainfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
