# Generated by Django 5.0.1 on 2024-03-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_declaratie_app', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraUserInformations',
        ),
    ]
