# Generated by Django 5.0.1 on 2024-02-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100)),
                ('company_manager', models.CharField(max_length=100)),
                ('company_cui', models.CharField(max_length=100)),
                ('company_register_number', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('company_location', models.CharField(max_length=100)),
                ('company_city', models.CharField(max_length=100)),
                ('contact_person_phone', models.CharField(max_length=100)),
            ],
        ),
    ]
