# Generated by Django 5.0.1 on 2024-02-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0008_company_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
    ]
