# Generated by Django 5.0.1 on 2024-02-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0009_alter_company_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='Companies',
        ),
    ]
