# Generated by Django 5.0.1 on 2024-02-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0010_alter_company_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_cui',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
