# Generated by Django 5.0.1 on 2024-02-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0011_alter_company_company_cui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_cui',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_register_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person_phone',
            field=models.CharField(max_length=25),
        ),
    ]
