# Generated by Django 5.0.1 on 2024-02-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0014_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_cui',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_register_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person_phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
    ]
