# Generated by Django 5.0.1 on 2024-02-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0023_alter_company_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
