# Generated by Django 5.0.1 on 2024-02-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0024_alter_company_contact_person_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_location',
        ),
    ]
