# Generated by Django 5.0.1 on 2024-03-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0027_alter_company_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
