# Generated by Django 5.0.1 on 2024-03-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0029_extrauserinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='extrauserinfo',
            table='ExtraUserInformation',
        ),
    ]
