# Generated by Django 5.0.1 on 2024-03-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0030_alter_extrauserinfo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrauserinfo',
            options={'verbose_name': 'Extra User Informations', 'verbose_name_plural': 'Extra User Informations'},
        ),
        migrations.AlterModelTable(
            name='extrauserinfo',
            table='Extra User Informations',
        ),
    ]
