# Generated by Django 5.0.1 on 2024-03-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0031_alter_extrauserinfo_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraUserInfo',
        ),
    ]
