# Generated by Django 5.0.1 on 2024-03-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0032_delete_extrauserinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
