# Generated by Django 5.0.1 on 2024-03-12 17:08

import user_company_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_company_app', '0004_alter_company_contact_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=user_company_app.models.company_directory_path),
        ),
    ]
