# Generated by Django 5.0.1 on 2024-04-02 09:42

import django.db.models.deletion
import user_company_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_company_app', '0005_company_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_content', models.TextField(blank=True, null=True)),
                ('company_stamp', models.ImageField(blank=True, null=True, upload_to=user_company_app.models.company_stamp_path)),
                ('pdf_declaration', models.FileField(blank=True, null=True, upload_to=user_company_app.models.pdf_declaration_path)),
                ('extend_company_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_company_app.company')),
            ],
        ),
    ]
