# Generated by Django 5.0.1 on 2024-03-02 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_extrauserinfo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='extrauserinfo',
            table=None,
        ),
    ]
