# Generated by Django 5.0.1 on 2024-03-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_extrauserinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrauserinfo',
            old_name='user',
            new_name='extra_user',
        ),
    ]
