# Generated by Django 5.0.1 on 2024-03-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_user_extrauserinfo_extra_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraUserInfo',
        ),
    ]
