# Generated by Django 5.0.1 on 2024-03-03 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100, unique=True)),
                ('company_cui', models.CharField(max_length=50, unique=True)),
                ('company_register_number', models.CharField(max_length=50, unique=True)),
                ('company_address', models.CharField(max_length=100)),
                ('company_city', models.CharField(max_length=50)),
                ('contact_person_phone', models.CharField(blank=True, max_length=25)),
                ('managers', models.ManyToManyField(blank=True, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Companies',
            },
        ),
    ]
