# Generated by Django 5.0.1 on 2024-04-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_extendcompanymodel_declaration_content'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='companies',
        ),
    ]
