# Generated by Django 5.0.1 on 2024-05-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_company_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
